#!/usr/bin/env node
/**
 * One version number for the whole tool. The root `package.json` "version" is the source of truth;
 * this script copies it to every other place that carries a version.
 *
 *   node scripts/sync-version.mjs                      stamp the root version everywhere
 *   node scripts/sync-version.mjs --set 0.19.0         set the root version, then stamp
 *   node scripts/sync-version.mjs --check              exit 1 if anything differs (no writes)
 *   node scripts/sync-version.mjs --check --tag v0.19.0   also require the tag to match
 *   node scripts/sync-version.mjs --release-manifest v0.19.0 build/module.json
 *                                                      write a module.json whose manifest and
 *                                                      download URLs point at that tag's release
 *
 * Stamped places: every workspace package.json, packages/foundry-module/module.json, the workspace
 * entries in package-lock.json, shared/src/version.ts (TOOL_VERSION, read by code at runtime) and
 * the fallback version in the NSIS script.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const rel = p => path.join(repoRoot, ...p.split('/'));
const read = p => readFileSync(rel(p), 'utf8');
const readJson = p => JSON.parse(read(p));
const writeText = (p, text) => writeFileSync(rel(p), text);
const writeJson = (p, data) => writeText(p, `${JSON.stringify(data, null, 2)}\n`);

const REPO_URL = (
  process.env.RELEASE_REPO_URL ?? 'https://github.com/Gnuminator/Foundry-VTT-MCP-Ai-Tool'
).replace(/\/+$/, '');
const SEMVER = /^\d+\.\d+\.\d+(-[0-9A-Za-z.-]+)?$/;
const WORKSPACE_PACKAGES = [
  'shared/package.json',
  'packages/cogm-dashboard/package.json',
  'packages/foundry-module/package.json',
  'packages/mcp-server/package.json',
];
const MODULE_JSON = 'packages/foundry-module/module.json';
const VERSION_TS = 'shared/src/version.ts';
const NSIS = 'installer/nsis/foundry-mcp-server.nsi';

const argv = process.argv.slice(2);
const flag = name => argv.includes(name);
const valueOf = name => {
  const i = argv.indexOf(name);
  return i >= 0 ? argv[i + 1] : undefined;
};
const fail = message => {
  console.error(`sync-version: ${message}`);
  process.exit(1);
};

function versionTsText(version) {
  return [
    '/**',
    ' * The tool version. Generated by `scripts/sync-version.mjs` from the root package.json: do not',
    ' * edit by hand (run `npm run version:sync`). The bridge and the Foundry module compare it to',
    ' * detect a mismatched pair.',
    ' */',
    `export const TOOL_VERSION = '${version}';`,
    '',
  ].join('\n');
}

/** The entries of package-lock.json that describe this repo's own packages. */
function lockEntries(lock) {
  return Object.entries(lock.packages ?? {}).filter(
    ([key]) =>
      key === '' ||
      key === 'shared' ||
      (key.startsWith('packages/') && !key.includes('node_modules'))
  );
}

/** Every stamped place as { label, current(), apply(version) }. */
function targets() {
  const list = [];
  for (const file of WORKSPACE_PACKAGES) {
    list.push({
      label: file,
      current: () => readJson(file).version,
      apply: v => writeJson(file, { ...readJson(file), version: v }),
    });
  }
  list.push({
    label: MODULE_JSON,
    current: () => readJson(MODULE_JSON).version,
    apply: v => writeJson(MODULE_JSON, { ...readJson(MODULE_JSON), version: v }),
  });
  list.push({
    label: 'package-lock.json (workspace entries)',
    current: () => {
      const lock = readJson('package-lock.json');
      const versions = new Set([lock.version, ...lockEntries(lock).map(([, e]) => e.version)]);
      return versions.size === 1 ? [...versions][0] : `mixed (${[...versions].join(', ')})`;
    },
    apply: v => {
      const lock = readJson('package-lock.json');
      lock.version = v;
      for (const [, entry] of lockEntries(lock)) entry.version = v;
      writeJson('package-lock.json', lock);
    },
  });
  list.push({
    label: VERSION_TS,
    current: () => /TOOL_VERSION = '([^']+)'/.exec(read(VERSION_TS))?.[1] ?? '(missing)',
    apply: v => writeText(VERSION_TS, versionTsText(v)),
  });
  list.push({
    label: NSIS,
    current: () => {
      const text = read(NSIS);
      const a = /!define VERSION "v([^"]+)"/.exec(text)?.[1];
      const b = /"DisplayVersion" "([^"]+)"/.exec(text)?.[1];
      return a === b ? (a ?? '(missing)') : `mixed (${a}, ${b})`;
    },
    apply: v =>
      writeText(
        NSIS,
        read(NSIS)
          .replace(/(!define VERSION ")v[^"]+(")/, `$1v${v}$2`)
          .replace(/("DisplayVersion" ")[^"]+(")/, `$1${v}$2`)
      ),
  });
  return list;
}

const releaseTag = valueOf('--release-manifest');
if (releaseTag !== undefined) {
  const outFile = argv[argv.indexOf('--release-manifest') + 2];
  if (!outFile) fail('usage: --release-manifest <tag> <outFile>');
  const version = readJson('package.json').version;
  if (releaseTag !== `v${version}`) {
    fail(`tag ${releaseTag} does not match the root version v${version}`);
  }
  const manifest = readJson(MODULE_JSON);
  manifest.version = version;
  manifest.manifest = `${REPO_URL}/releases/download/${releaseTag}/module.json`;
  manifest.download = `${REPO_URL}/releases/download/${releaseTag}/foundry-mcp-bridge.zip`;
  mkdirSync(path.dirname(path.resolve(outFile)), { recursive: true });
  writeFileSync(path.resolve(outFile), `${JSON.stringify(manifest, null, 2)}\n`);
  console.log(`sync-version: wrote ${outFile} for ${releaseTag}`);
  process.exit(0);
}

const setTo = valueOf('--set');
if (setTo !== undefined) {
  if (!SEMVER.test(setTo)) fail(`"${setTo}" is not a version like 1.2.3`);
  writeJson('package.json', { ...readJson('package.json'), version: setTo });
}

const version = readJson('package.json').version;
if (!SEMVER.test(version))
  fail(`root package.json version "${version}" is not a version like 1.2.3`);

if (flag('--check')) {
  const problems = [];
  const tag = valueOf('--tag');
  if (tag !== undefined && tag !== `v${version}`) {
    problems.push(`tag ${tag} does not match the root version v${version}`);
  }
  for (const target of targets()) {
    const current = target.current();
    if (current !== version) problems.push(`${target.label}: ${current} (expected ${version})`);
  }
  if (problems.length > 0) {
    console.error(`sync-version: version mismatch (root is ${version}):`);
    console.error(problems.map(p => `  ${p}`).join('\n'));
    console.error('Fix with: npm run version:sync');
    process.exit(1);
  }
  console.log(`sync-version: OK, everything is ${version}.`);
  process.exit(0);
}

let changed = 0;
for (const target of targets()) {
  const before = target.current();
  if (before === version) continue;
  target.apply(version);
  changed++;
  console.log(`  ${target.label}: ${before} -> ${version}`);
}
console.log(
  changed === 0
    ? `sync-version: already ${version} everywhere.`
    : `sync-version: stamped ${version}.`
);
