/**
 * The ownership guard (docs/design/OBSIDIAN-PLAN.md O2 item 1): a generated note's
 * hash round-trips, an edited note is detected, and a legacy O1 note is
 * recognized for one-time migration.
 */
import { createHash } from 'crypto';

import { describe, expect, it } from 'vitest';

import {
  BASE_CHANGED_REASON,
  baseOwnershipCheck,
  checkCanvasOwnership,
  checkMarkdownOwnership,
  renderBaseText,
  withCanvasHash,
  withGeneratedHash,
  type CanvasMarkerDoc,
} from './ownership.js';

const MD = [
  '---',
  'type: "session"',
  'fvtt_world: "test-world"',
  'generated_by: "foundry-ai-tool"',
  'generated_hash: ""',
  '---',
  '# Hello',
].join('\n');

describe('Markdown ownership', () => {
  it('round-trips: a freshly built note is recognized as owned and unedited', () => {
    const text = withGeneratedHash(MD);
    expect(text).toMatch(/generated_hash: "[0-9a-f]{16}"/);
    expect(checkMarkdownOwnership(text)).toEqual({ owned: true, legacy: false });
  });

  it('flags a hash mismatch (the GM edited the note) as not owned', () => {
    const text = withGeneratedHash(MD).replace('# Hello', '# Hello, edited by the GM');
    expect(checkMarkdownOwnership(text)).toEqual({ owned: false, reason: 'edited in Obsidian' });
  });

  it('recognizes a legacy O1 note (generated: true + the O1 banner) as owned', () => {
    const legacy = [
      '---',
      'type: "session-log"',
      'world: "test-world"',
      'generated: true',
      '---',
      '# Session log',
      '',
      '> [!info] Generated by the Foundry AI Tool',
      '> Body text.',
    ].join('\n');
    expect(checkMarkdownOwnership(legacy)).toEqual({ owned: true, legacy: true });
  });

  it('treats a note with no marker at all as foreign', () => {
    expect(checkMarkdownOwnership('# My own note\n\nSome prep text.')).toEqual({
      owned: false,
      reason: 'not written by the AI Tool',
    });
  });

  it('withGeneratedHash refuses text with no placeholder property', () => {
    expect(() => withGeneratedHash('# no frontmatter here')).toThrow(/generated_hash/);
  });
});

function canvasDoc(): CanvasMarkerDoc {
  return {
    nodes: [
      { id: 'tome', type: 'text', text: 'Tome', x: 0, y: 0, width: 100, height: 100 },
      { id: 'generated', type: 'text', text: '', x: -100, y: -100, width: 100, height: 100 },
    ],
    edges: [],
  };
}

describe('Canvas ownership', () => {
  it('round-trips: a freshly built canvas is recognized as owned', () => {
    const text = withCanvasHash(canvasDoc(), 'Generated banner');
    expect(checkCanvasOwnership(text)).toEqual({ owned: true, legacy: false });
    const parsed = JSON.parse(text) as CanvasMarkerDoc;
    const marker = parsed.nodes.find(n => n.id === 'generated');
    expect(marker?.text).toContain('generated_by: foundry-ai-tool');
    expect(marker?.text).toMatch(/generated_hash: [0-9a-f]+$/);
  });

  it('is whitespace-independent (re-serializing the parsed JSON does not look edited)', () => {
    const text = withCanvasHash(canvasDoc(), 'Generated banner');
    const reformatted = JSON.stringify(JSON.parse(text), null, 2);
    expect(checkCanvasOwnership(reformatted)).toEqual({ owned: true, legacy: false });
  });

  it('flags a real content edit as not owned', () => {
    const text = withCanvasHash(canvasDoc(), 'Generated banner');
    const parsed = JSON.parse(text) as CanvasMarkerDoc;
    const tome = parsed.nodes.find(n => n.id === 'tome');
    if (tome) tome.text = 'Edited by the GM';
    expect(checkCanvasOwnership(JSON.stringify(parsed))).toEqual({
      owned: false,
      reason: 'edited in Obsidian',
    });
  });

  it('treats invalid JSON or a missing marker node as foreign', () => {
    expect(checkCanvasOwnership('not json')).toEqual({
      owned: false,
      reason: 'not written by the AI Tool',
    });
    expect(
      checkCanvasOwnership(JSON.stringify({ nodes: [{ id: 'x', text: 'hi' }], edges: [] }))
    ).toEqual({ owned: false, reason: 'not written by the AI Tool' });
  });
});

describe('Base file ownership', () => {
  const body = 'filters:\n  and:\n    - file.hasTag("session")\n';

  it('writes no marker (Obsidian drops comments when it re-saves a base)', () => {
    expect(renderBaseText(body)).toBe(body);
    expect(renderBaseText('name: <% tp.file.title %>\n')).not.toContain('<%');
  });

  it('owns a base whose content matches, also after Obsidian re-saved it', () => {
    const check = baseOwnershipCheck(renderBaseText(body));
    expect(check(body)).toEqual({ owned: true, legacy: false, same: true });
    // Re-saved: trailing spaces and the final newline differ.
    expect(check('filters:  \n  and:\n    - file.hasTag("session")')).toMatchObject({
      owned: true,
      same: true,
    });
  });

  it('owns a base written with the early O2 comment marker while its hash matches', () => {
    const old = 'filters:\n  and:\n    - file.hasTag("old")\n';
    const blanked = `# generated_by: foundry-ai-tool\n# generated_hash: \n${old}`;
    const hash = createHash('sha256').update(blanked, 'utf8').digest('hex').slice(0, 16);
    const marked = `# generated_by: foundry-ai-tool\n# generated_hash: ${hash}\n${old}`;
    expect(baseOwnershipCheck(body)(marked)).toEqual({ owned: true, legacy: true });
    expect(baseOwnershipCheck(body)(marked.replace('"old"', '"edited"'))).toEqual({
      owned: false,
      reason: BASE_CHANGED_REASON,
    });
  });

  it('leaves a base changed in Obsidian alone', () => {
    const changed = body.replace('file.hasTag("session")', 'file.hasTag("mine")');
    expect(baseOwnershipCheck(body)(changed)).toEqual({
      owned: false,
      reason: BASE_CHANGED_REASON,
    });
  });
});
