/**
 * Ownership guard for notes the exporter writes into the GM's Obsidian vault
 * (docs/design/OBSIDIAN-PLAN.md, O2 item 1). Every generated `.md` and `.canvas` file
 * carries a marker plus a content hash (a `.base` is compared by content, see
 * below). Before overwriting an existing file the exporter checks the hash
 * still matches the text on disk; a note the GM edited by hand fails the check
 * and is left alone (and listed in `_status.md`) instead of being rebuilt over
 * the GM's edits.
 *
 * Two eras of marker:
 * - O2 marker: frontmatter `generated_by: "foundry-ai-tool"` plus, as the last
 *   property, `generated_hash: "<16 hex>"` (the first 16 hex chars of sha256
 *   over the full note text with that property's value blanked to `""`).
 * - O1 legacy marker (no hash yet): frontmatter `generated: true` plus the O1
 *   banner line. Treated as ours, unedited, once (a one-time migration).
 *
 * The GM's vault also runs the Templater community plugin, so every note that
 * embeds data we did not write ourselves (event descriptions, actor and scene
 * names, chat text, change summaries and diff lines, card names, GM notes,
 * reading ids) is passed through {@link neutralizeTemplater} before it is
 * hashed: `withGeneratedHash`/`withCanvasHash`/`renderBaseText` are the single
 * choke point every generated note passes through, so nothing written ever
 * carries a literal `<%` a malicious actor/scene/chat name could plant to run
 * as a Templater command when the GM opens the note.
 */
import { createHash } from 'crypto';

export const GENERATED_BY = 'foundry-ai-tool';

/** Neutralize Templater's opening tag: renders as the literal text `<%` in
 * Obsidian, but Templater no longer matches it as a command. */
export function neutralizeTemplater(text: string): string {
  return text.replace(/<%/g, '&lt;%');
}

const MARKER_PROPERTY_LINE = `generated_by: "${GENERATED_BY}"`;
const HASH_PROPERTY = /^generated_hash: "([0-9a-f]*)"$/m;

const LEGACY_PROPERTY = 'generated: true';
const LEGACY_BANNER_LINE = '> [!info] Generated by the Foundry AI Tool';

const BASE_MARKER_LINE = `# generated_by: ${GENERATED_BY}`;
const BASE_HASH_PREFIX = '# generated_hash: ';

export type OwnershipResult =
  /** `same`: the file already holds our content in another form (no write needed). */
  | { owned: true; legacy: boolean; same?: boolean }
  | {
      owned: false;
      reason: 'edited in Obsidian' | 'not written by the AI Tool' | typeof BASE_CHANGED_REASON;
    };

function sha16(text: string): string {
  return createHash('sha256').update(text, 'utf8').digest('hex').slice(0, 16);
}

// ---------------------------------------------------------------------------
// Markdown notes (frontmatter property)
// ---------------------------------------------------------------------------

/** Fill a Markdown note's blank `generated_hash: ""` placeholder with its
 * hash, after neutralizing any Templater tag anywhere in the text. */
export function withGeneratedHash(text: string): string {
  const clean = neutralizeTemplater(text);
  const match = HASH_PROPERTY.exec(clean);
  if (!match) throw new Error('Note text has no generated_hash property to fill');
  const hash = sha16(clean);
  return `${clean.slice(0, match.index)}generated_hash: "${hash}"${clean.slice(match.index + match[0].length)}`;
}

/** Whether an existing Markdown note is ours (unedited) or a migratable O1 note. */
export function checkMarkdownOwnership(existingText: string): OwnershipResult {
  if (existingText.includes(MARKER_PROPERTY_LINE)) {
    const match = HASH_PROPERTY.exec(existingText);
    if (match) {
      const blanked = `${existingText.slice(0, match.index)}generated_hash: ""${existingText.slice(match.index + match[0].length)}`;
      if (sha16(blanked) === match[1]) return { owned: true, legacy: false };
    }
    return { owned: false, reason: 'edited in Obsidian' };
  }
  if (existingText.includes(LEGACY_PROPERTY) && existingText.includes(LEGACY_BANNER_LINE)) {
    return { owned: true, legacy: true };
  }
  return { owned: false, reason: 'not written by the AI Tool' };
}

// ---------------------------------------------------------------------------
// Canvas files (a marker node, hash over the re-parsed JSON so formatting
// changes that leave the data unchanged do not look like an edit)
// ---------------------------------------------------------------------------

export interface CanvasMarkerDoc {
  nodes: Array<{ id: string; text?: unknown; [key: string]: unknown }>;
  [key: string]: unknown;
}

function withMarkerText(doc: CanvasMarkerDoc, text: string): CanvasMarkerDoc {
  return {
    ...doc,
    nodes: doc.nodes.map(node => (node.id === 'generated' ? { ...node, text } : node)),
  };
}

function neutralizeNodeTexts(doc: CanvasMarkerDoc): CanvasMarkerDoc {
  return {
    ...doc,
    nodes: doc.nodes.map(node =>
      typeof node.text === 'string' ? { ...node, text: neutralizeTemplater(node.text) } : node
    ),
  };
}

/** Build the final canvas JSON text: fills the "generated" node's text with the
 * banner and hash, after neutralizing any Templater tag in every node's text.
 * The hash is computed over the parsed doc with that node's text blanked to
 * `""`, so re-serialization whitespace never matters. */
export function withCanvasHash(doc: CanvasMarkerDoc, bannerText: string): string {
  const clean = neutralizeNodeTexts(doc);
  const hash = sha16(JSON.stringify(withMarkerText(clean, '')));
  const markerText = neutralizeTemplater(
    `${bannerText}\ngenerated_by: ${GENERATED_BY}\ngenerated_hash: ${hash}`
  );
  return JSON.stringify(withMarkerText(clean, markerText), null, '\t');
}

export function checkCanvasOwnership(existingText: string): OwnershipResult {
  let parsed: unknown;
  try {
    parsed = JSON.parse(existingText);
  } catch {
    return { owned: false, reason: 'not written by the AI Tool' };
  }
  const doc = parsed as Partial<CanvasMarkerDoc> | null;
  if (!doc || !Array.isArray(doc.nodes))
    return { owned: false, reason: 'not written by the AI Tool' };
  const marker = doc.nodes.find(node => node?.id === 'generated');
  const text = typeof marker?.text === 'string' ? marker.text : null;
  if (!text?.includes(`generated_by: ${GENERATED_BY}`)) {
    return { owned: false, reason: 'not written by the AI Tool' };
  }
  const match = /^generated_hash: ([0-9a-f]+)$/m.exec(text);
  if (!match) return { owned: false, reason: 'edited in Obsidian' };
  const hash = sha16(JSON.stringify(withMarkerText(doc as CanvasMarkerDoc, '')));
  return hash === match[1]
    ? { owned: true, legacy: false }
    : { owned: false, reason: 'edited in Obsidian' };
}

// ---------------------------------------------------------------------------
// .base files. Obsidian re-saves a base when it is opened and drops comments,
// so a base carries no marker: it counts as ours while its content still
// matches what we generate (comment lines and trailing whitespace ignored). A
// base changed in Obsidian is left alone; deleting it brings ours back.
// ---------------------------------------------------------------------------

export const BASE_CHANGED_REASON =
  'changed in Obsidian (delete the file to get the AI Tool version back)';

/** The text of a generated base: its body, neutralized against Templater. */
export function renderBaseText(body: string): string {
  return neutralizeTemplater(body);
}

function normalizeBase(text: string): string {
  return text
    .split(/\r?\n/)
    .filter(line => !/^\s*#/.test(line))
    .map(line => line.trimEnd())
    .join('\n')
    .trim();
}

/** A base written with the early O2 comment marker (`# generated_by` plus a hash
 * over the text with the hash blanked) whose hash still matches: ours. */
function hasValidBaseMarker(text: string): boolean {
  const lines = text.split('\n');
  const hashLine = lines[1] ?? '';
  if (lines[0] !== BASE_MARKER_LINE || !hashLine.startsWith(BASE_HASH_PREFIX)) return false;
  const claimed = hashLine.slice(BASE_HASH_PREFIX.length);
  const blanked = `${BASE_MARKER_LINE}\n${BASE_HASH_PREFIX}\n${lines.slice(2).join('\n')}`;
  return /^[0-9a-f]+$/.test(claimed) && sha16(blanked) === claimed;
}

/** The ownership check for one base, against the text we would write now. */
export function baseOwnershipCheck(expected: string): (existingText: string) => OwnershipResult {
  const want = normalizeBase(expected);
  return existingText => {
    if (normalizeBase(existingText) === want) return { owned: true, legacy: false, same: true };
    if (hasValidBaseMarker(existingText)) return { owned: true, legacy: true };
    return { owned: false, reason: BASE_CHANGED_REASON };
  };
}
