import { promises as fsp } from 'fs';
import * as os from 'os';
import * as path from 'path';

import { usageLogFileName, type UsageCatalogEntry, type UsageEvent } from '@gnuminator/shared';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import { buildUsageModel } from '../stats/usage.js';
import { usageEvent } from '../test-support/usage-events.js';
import { AuditLog } from '../vault/audit.js';
import { VaultStore } from '../vault/store.js';

import { campaignDir, exportWorldToObsidian, newExportCache } from './export.js';
import { formatUsageDuration, renderUsageNote, USAGE_NOTE_PATH } from './render-usage.js';

const T = new Date(2026, 8, 28, 20, 0, 0).getTime();
const MIN = 60_000;
const WORLD = 'usage-world';

const CATALOG: UsageCatalogEntry[] = [
  { name: 'dash.tarokka.roll', kind: 'action', surface: 'dashboard', file: 'a.js' },
  { name: 'dash.tarokka.reveal', kind: 'action', surface: 'dashboard', file: 'a.js' },
  { name: 'player.handouts.open', kind: 'action', surface: 'player', file: 'p.js' },
];

function sampleEvents(): UsageEvent[] {
  return [
    usageEvent({ t: T + MIN, name: 'dash.tarokka.roll', count: 2 }),
    usageEvent({ t: T + 2 * MIN, name: 'dash.main.view', kind: 'view', durationMs: 125_000 }),
    usageEvent({ t: T + 3 * MIN, name: 'tool.get-world-info', kind: 'tool', outcome: 'ok' }),
    usageEvent({ t: T + 4 * MIN, name: 'dash.toast.error', kind: 'error', code: 'timeout' }),
    usageEvent({
      t: T + 5 * MIN,
      surface: 'player',
      name: 'player.handouts.open',
      who: { role: 'player', userId: 'u1', name: '<%* evil %> | Ada' },
    }),
    usageEvent({ t: T + 6 * MIN, name: 'dash.gone.control' }),
  ];
}

describe('formatUsageDuration', () => {
  it('formats seconds, minutes and hours', () => {
    expect(formatUsageDuration(0)).toBe('0s');
    expect(formatUsageDuration(45_000)).toBe('45s');
    expect(formatUsageDuration(12 * MIN)).toBe('12m');
    expect(formatUsageDuration(65 * MIN)).toBe('1h 05m');
  });
});

describe('renderUsageNote', () => {
  const model = buildUsageModel({
    events: sampleEvents(),
    catalog: CATALOG,
    toolNames: ['get-world-info', 'list-scenes'],
    sessions: [
      {
        label: '2026-09-28 S01',
        startedAt: new Date(T).toISOString(),
        endedAt: new Date(T + 30 * MIN).toISOString(),
      },
    ],
  });
  const note = renderUsageNote(WORLD, model);

  it('carries the generated properties, banner and every section', () => {
    expect(note).toMatch(/^---\ntype: "usage"\nfvtt_world: "usage-world"\nevents: 7\n/);
    expect(note).toContain('player_visible: false');
    expect(note).toContain('generated_by:');
    expect(note).toContain('# Dashboard usage');
    expect(note).toContain('> [!info] Generated by the Foundry AI Tool');
    for (const heading of [
      '## Period and totals',
      '## Most used',
      '## Never used',
      '### Dashboard',
      '### Player page',
      '### Foundry module',
      '### Tools never run from the tool runner',
      '## Per person',
      '## Per session',
      '## Errors',
      '## Unknown names',
    ]) {
      expect(note).toContain(heading);
    }
  });

  it('shows totals, most used rows, never-used controls and tools', () => {
    expect(note).toContain('2026-09-28 to 2026-09-28 (1 days with activity).');
    expect(note).toContain('| 7 | 1 | 2m | 4 | 0 | 1 | 1 | 2 |');
    expect(note).toContain('| `dash.tarokka.roll` | action | 2 |');
    expect(note).toContain('- `dash.tarokka.reveal` (action)');
    expect(note).toContain('- `list-scenes`');
    expect(note).toContain('Everything in the catalogue was used at least once.');
  });

  it('links sessions, lists errors and unknown names', () => {
    expect(note).toContain('| [[2026-09-28 S01]] | 7 | 2 |');
    expect(note).toContain('| `dash.toast.error` | timeout | 1 |');
    expect(note).toContain('| `dash.gone.control` | 1 |');
    expect(note).toContain('| `dash.main.view` | 1 |');
  });

  it('neutralizes Templater tags and pipes in people names', () => {
    expect(note).not.toContain('<%');
    expect(note).toContain('&lt;%');
    expect(note).toContain('\\| Ada');
  });

  it('is deterministic', () => {
    expect(renderUsageNote(WORLD, model)).toBe(note);
  });

  it('says so when there is nothing recorded and when the tool list is missing', () => {
    const empty = renderUsageNote(
      WORLD,
      buildUsageModel({ events: [], catalog: CATALOG, toolNames: null, sessions: [] })
    );
    expect(empty).toContain('No usage recorded yet.');
    expect(empty).toContain('(tool list not available in this export)');
    expect(empty).toContain('- `dash.tarokka.roll` (action)');
  });
});

describe('export of the usage note', () => {
  let dataDir: string;
  let vaultDir: string;
  let store: VaultStore;

  beforeEach(async () => {
    dataDir = await fsp.mkdtemp(path.join(os.tmpdir(), 'usage-data-'));
    vaultDir = await fsp.mkdtemp(path.join(os.tmpdir(), 'usage-vault-'));
    store = new VaultStore({ dataDir });
  });

  afterEach(async () => {
    await fsp.rm(dataDir, { recursive: true, force: true });
    await fsp.rm(vaultDir, { recursive: true, force: true });
  });

  async function read(rel: string): Promise<string | null> {
    return fsp.readFile(path.join(campaignDir(vaultDir, WORLD), rel), 'utf8').catch(() => null);
  }

  async function run(
    toolNames: readonly string[] | null,
    cache = newExportCache()
  ): Promise<string[]> {
    const result = await exportWorldToObsidian({
      store,
      audit: new AuditLog(store),
      worldId: WORLD,
      vaultDir,
      cache,
      toolNames,
    });
    expect(result.errors).toEqual([]);
    return result.written;
  }

  it('writes no usage note and no link while the world has no usage events', async () => {
    await run(['get-world-info']);
    expect(await read(USAGE_NOTE_PATH)).toBeNull();
    expect(await read('AI Tool/Stats/Campaign.md')).not.toContain('Dashboard usage');
  });

  it('writes the note from the day files, links it from Campaign.md and reuses the cache', async () => {
    await store.appendLines(
      WORLD,
      'sessions',
      usageLogFileName('2026-09-28'),
      sampleEvents().slice(0, 3)
    );
    await store.appendLines(WORLD, 'sessions', usageLogFileName('2026-09-28'), [
      { garbage: true },
      'not an event',
    ]);
    const cache = newExportCache();
    await run(['get-world-info', 'list-scenes'], cache);
    const note = await read(USAGE_NOTE_PATH);
    expect(note).toContain('# Dashboard usage');
    expect(note).toContain('| `dash.tarokka.roll` | action | 2 |');
    expect(note).toContain('- `list-scenes`');
    expect(cache.usageLogs.size).toBe(1);
    const campaign = await read('AI Tool/Stats/Campaign.md');
    expect(campaign).toContain('[[Dashboard usage]]');

    // New lines appended later show up (size changed), an unchanged export rewrites nothing.
    await store.appendLines(WORLD, 'sessions', usageLogFileName('2026-09-29'), [
      usageEvent({ t: T + 24 * 60 * MIN, name: 'dash.tarokka.roll' }),
    ]);
    const written = await run(['get-world-info', 'list-scenes'], cache);
    expect(written).toContain(USAGE_NOTE_PATH);
    expect(await read(USAGE_NOTE_PATH)).toContain('2026-09-28 to 2026-09-29 (2 days');
    const again = await run(['get-world-info', 'list-scenes'], cache);
    expect(again).not.toContain(USAGE_NOTE_PATH);
  });

  it('leaves the tools-never-run list out when no tool list is given', async () => {
    await store.appendLines(WORLD, 'sessions', usageLogFileName('2026-09-28'), sampleEvents());
    await run(null);
    expect(await read(USAGE_NOTE_PATH)).toContain('(tool list not available in this export)');
  });
});
