/**
 * Obsidian notes rendered from the bridge vault (docs/design/OBSIDIAN-PLAN.md, O1+O2).
 *
 * Pure functions: vault data in, Markdown/JSON-Canvas/Base text out. The
 * bridge vault stays the source of truth; these notes are a read-only,
 * GM-only view of it that the exporter writes into the GM's Obsidian vault
 * under `Campaigns/<worldId>/AI Tool/`. Output is deterministic (no
 * timestamps of the export itself), so an unchanged note is not rewritten
 * while the GM has it open.
 *
 * Every generated note ends with `withGeneratedHash`/`withCanvasHash` (see
 * `ownership.ts`): a `generated_by` marker plus a content hash the exporter
 * checks before overwriting, so a note the GM edited by hand is left alone.
 * Bases go through `renderBaseText` and are compared by content instead
 * (Obsidian re-saves a base when it is opened).
 *
 * Conventions: flat YAML properties (text, number, checkbox, list), Markdown
 * links (docs/design/OBSIDIAN-PLAN.md 12.2: Markdown links vault-wide), a banner on
 * every note saying it is generated, and secrets (card names, diffs that may
 * contain them) inside collapsed callouts so they do not show at a glance.
 */
import type { CombatStats, PcStats, SessionStats, StatsModel, Tally } from '../stats/types.js';

import type { ChangeEntry } from './audit-merge.js';
import {
  eventTimeMs,
  sessionLabel,
  type EndedBy,
  type SessionEvent,
  type StartedBy,
} from './grouping.js';
import { encodeSegment } from './mirror-common.js';
import {
  GENERATED_BY,
  neutralizeTemplater,
  renderBaseText,
  withCanvasHash,
  withGeneratedHash,
  type CanvasMarkerDoc,
} from './ownership.js';

export const GENERATED_BANNER =
  '> [!info] Generated by the Foundry AI Tool\n' +
  '> This note is rebuilt from the bridge vault on every export; edits here are lost. ' +
  'Write your own notes in `Prep/`.';

type PropValue = string | number | boolean | null | readonly string[];

function yamlScalar(value: string | number | boolean | null): string {
  if (value === null) return 'null';
  if (typeof value === 'number' || typeof value === 'boolean') return String(value);
  // Quote everything textual: safe for colons, links, leading symbols, and
  // neutralized against Templater (the GM's vault runs that plugin).
  return JSON.stringify(neutralizeTemplater(value));
}

/** A YAML properties block (flat keys only, as Obsidian properties expect). */
export function frontmatter(props: Record<string, PropValue | undefined>): string {
  const lines = ['---'];
  for (const [key, value] of Object.entries(props)) {
    if (value === undefined) continue;
    if (Array.isArray(value)) {
      const list = value as readonly string[];
      if (list.length === 0) {
        lines.push(`${key}: []`);
      } else {
        lines.push(`${key}:`);
        for (const item of list) lines.push(`  - ${yamlScalar(item)}`);
      }
    } else {
      lines.push(`${key}: ${yamlScalar(value as string | number | boolean | null)}`);
    }
  }
  lines.push('---');
  return lines.join('\n');
}

/** The common properties every generated note carries, in a fixed order:
 * `type`, `fvtt_world`, the type's own properties, `fvtt_modified`,
 * `player_visible`, `schema`, `tags`, then the ownership marker (its hash is
 * a placeholder here; `withGeneratedHash` fills it in). `playerVisible` is
 * advisory for the GM only (docs/design/OBSIDIAN-O4-DESIGN.md section 4); every O2
 * note leaves it at the default `false`, so their text stays byte-identical. */
export function generatedProps(
  type: string,
  worldId: string,
  typeProps: Record<string, PropValue | undefined>,
  fvttModified: string | null,
  playerVisible = false
): Record<string, PropValue | undefined> {
  return {
    type,
    fvtt_world: worldId,
    ...typeProps,
    fvtt_modified: fvttModified,
    player_visible: playerVisible,
    schema: 1,
    tags: [`campaign/${worldId}`, type],
    generated_by: GENERATED_BY,
    generated_hash: '',
  };
}

/** Text safe inside a Markdown table cell, and neutralized against Templater. */
export function cell(value: unknown): string {
  const text =
    typeof value === 'string'
      ? value
      : typeof value === 'number' || typeof value === 'boolean'
        ? String(value)
        : '';
  // The backslash is escaped with the pipe: data ending in `\` must not turn `\|` into `\\|`,
  // an escaped backslash followed by a live column break.
  return neutralizeTemplater(text.replace(/\r?\n/g, ' ').replace(/[\\|]/g, '\\$&').trim());
}

/** A string safe as a file name on Windows, Linux and in Obsidian links. */
export function safeFileName(name: string): string {
  const printable = Array.from(name, ch => (ch.charCodeAt(0) < 32 ? ' ' : ch)).join('');
  const cleaned = printable
    .replace(/[<>:"/\\|?*#^[\]%]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .replace(/[. ]+$/, '');
  const reserved = /^(con|prn|aux|nul|com\d|lpt\d)$/i;
  if (!cleaned || reserved.test(cleaned)) return `_${cleaned || 'untitled'}`;
  return cleaned.slice(0, 120);
}

function callout(type: string, title: string, body: string[], collapsed = true): string {
  const head = `> [!${type}]${collapsed ? '-' : ''} ${neutralizeTemplater(title)}`;
  const lines = body.length ? body : ['(empty)'];
  return [head, ...lines.map(l => (l ? `> ${neutralizeTemplater(l)}` : '>'))].join('\n');
}

/** "2026-09-28T09:52:27.308Z" -> "2026-09-28 09:52" (UTC, stable across hosts). */
function shortTime(iso: string | null | undefined): string {
  if (!iso) return '';
  return iso.replace('T', ' ').slice(0, 16);
}

// ---------------------------------------------------------------------------
// Sessions (one note per play session, shared contract 3)
// ---------------------------------------------------------------------------

export type { SessionEvent };

export interface SessionGroupInput {
  events: SessionEvent[];
  startedBy: StartedBy;
  endedBy: EndedBy;
}

/** One note per play session: `AI Tool/Sessions/<date> S<NN>.md`. The
 * timeline table still comes from the session-log events alone (`group`);
 * `stats` (from `stats/build.ts`, contract 5) supplies the session's number,
 * label and bounds plus the O3 play-log properties and the Stats section, so
 * the note and `get-play-stats` always agree. */
export function renderSessionNote(
  worldId: string,
  group: SessionGroupInput,
  stats: SessionStats,
  /** Links to this day's recorded session notes in Foundry (D-087), as list lines. */
  sessionNotes: readonly string[] = []
): string {
  const sorted = [...group.events].sort((a, b) => eventTimeMs(a) - eventTimeMs(b));
  const types = [...new Set(sorted.map(e => e.eventType ?? 'event'))].sort();
  const actors = [
    ...new Set(sorted.map(e => e.actorName).filter((n): n is string => Boolean(n))),
  ].sort();
  // Changes/ notes are named by the UTC month a change was applied; the event
  // that logged a change carries its id at (about) that time.
  const changeMonths = new Map<string, string>();
  for (const e of sorted) {
    const id = e.details?.changeId;
    if (typeof id === 'string' && !changeMonths.has(id)) {
      changeMonths.set(id, new Date(eventTimeMs(e)).toISOString().slice(0, 7));
    }
  }
  const uniqueChangeIds = [...changeMonths.keys()];
  const scenes = [
    ...new Set(
      sorted
        .filter(e => e.eventType === 'scene-change')
        .map(e => (typeof e.details?.sceneName === 'string' ? e.details.sceneName : null))
        .filter((n): n is string => n !== null)
    ),
  ].sort();

  const props = generatedProps(
    'session',
    worldId,
    {
      session_number: stats.number,
      date: stats.date,
      started_at: stats.startedAt,
      ended_at: stats.endedAt,
      duration_min: stats.durationMin,
      started_by: group.startedBy,
      ended_by: group.endedBy,
      events: sorted.length,
      event_types: types,
      actors,
      changes: uniqueChangeIds.length,
      scenes,
      // O3 (docs/design/OBSIDIAN-PLAN.md section 8): play-log derived stats, built by
      // stats/build.ts over the same session (contract 5).
      play_records: stats.playRecords,
      combats: stats.combats.length,
      combat_rounds: stats.combatRounds,
      party_damage_dealt: stats.partyDamageDealt,
      party_damage_taken: stats.partyDamageTaken,
      party_healing: stats.partyHealing,
      pc_downs: stats.pcDowns,
      npc_kills: stats.npcKills,
      rolls: stats.rolls,
      crits: stats.crits,
      fumbles: stats.fumbles,
      spells_cast: stats.spellsCast,
      spell_slots_spent: stats.spellSlotsSpent,
      gm_changes: stats.gmChanges,
    },
    stats.endedAt
  );

  const rows = sorted.map(e => {
    const change = typeof e.details?.changeId === 'string' ? ` (${e.details.changeId})` : '';
    const time = e.timestamp ?? new Date(eventTimeMs(e)).toISOString();
    // Rolls: the GM's full breakdown (dice, each bonus, target and outcome).
    const breakdown = e.details?.breakdown;
    const what = typeof breakdown === 'string' && breakdown ? breakdown : (e.description ?? '');
    return `| ${cell(shortTime(time).slice(11))} | ${cell(e.eventType)} | ${cell(e.actorName)} | ${cell(`${what}${change}`)} |`;
  });
  const changeLinks = uniqueChangeIds.map(
    id => `- [${id}](../Changes/${changeMonths.get(id) ?? ''}.md#^${id})`
  );

  return withGeneratedHash(
    [
      frontmatter(props),
      `# ${stats.label}`,
      '',
      GENERATED_BANNER,
      '',
      `${sorted.length} event(s) in this play session (started by ${group.startedBy}, ended by ${group.endedBy}; times in UTC).`,
      '',
      '| Time | Type | Who | What |',
      '| --- | --- | --- | --- |',
      ...rows,
      '',
      ...(changeLinks.length ? ['## Changes', '', ...changeLinks, ''] : []),
      ...(sessionNotes.length ? ['## Session notes', '', ...sessionNotes, ''] : []),
      ...renderSessionStatsSection(stats),
    ].join('\n')
  );
}

function tallyLine(tally: Tally): string {
  const entries = Object.entries(tally);
  if (entries.length === 0) return '(none)';
  return entries.map(([name, n]) => `${neutralizeTemplater(name)} ${n}`).join(', ');
}

function renderCombatStatsBlock(combat: CombatStats, index: number): string[] {
  return [
    `### Combat ${index + 1}${combat.sceneName ? ` (${neutralizeTemplater(combat.sceneName)})` : ''}`,
    '',
    `- Rounds: ${combat.rounds}`,
    `- Participants: ${combat.participants.length ? combat.participants.map(p => neutralizeTemplater(p)).join(', ') : '(none)'}`,
    `- Damage taken: ${tallyLine(combat.damageTaken)}`,
    `- Damage dealt: ${tallyLine(combat.damageDealt)}`,
    `- Healing: ${tallyLine(combat.healing)}`,
    `- Downs: ${combat.downs.length ? combat.downs.map(n => neutralizeTemplater(n)).join(', ') : '(none)'}`,
    `- Kills: ${combat.kills.length ? combat.kills.map(n => neutralizeTemplater(n)).join(', ') : '(none)'}`,
    `- Crits: ${combat.crits} · Fumbles: ${combat.fumbles}`,
    '',
  ];
}

/** The session note's "Stats" section (O3): a one-line summary plus one block
 * per combat (rounds, damage taken/dealt, downs, kills). */
function renderSessionStatsSection(stats: SessionStats): string[] {
  return [
    '## Stats',
    '',
    `${stats.rolls} roll(s), ${stats.crits} crit(s), ${stats.fumbles} fumble(s). Party: ` +
      `${stats.partyDamageDealt} damage dealt, ${stats.partyDamageTaken} damage taken, ` +
      `${stats.partyHealing} healing. ${stats.pcDowns} PC down(s), ${stats.npcKills} NPC kill(s).`,
    '',
    ...(stats.highestRoll
      ? [
          `Highest roll: ${stats.highestRoll.total}, ${neutralizeTemplater(stats.highestRoll.name)}` +
            `${stats.highestRoll.label ? ` (${neutralizeTemplater(stats.highestRoll.label)})` : ''}.`,
          '',
        ]
      : []),
    ...(stats.combats.length
      ? stats.combats.flatMap((c, i) => renderCombatStatsBlock(c, i))
      : ['(no combats this session)', '']),
  ];
}

// ---------------------------------------------------------------------------
// Change log (audit)
// ---------------------------------------------------------------------------

export type { ChangeEntry };

/** One note per month of applied and undone guarded changes, newest first;
 * each change block ends with a `^<changeId>` block id line. */
export function renderChangesNote(worldId: string, month: string, entries: ChangeEntry[]): string {
  const sorted = [...entries].sort((a, b) => b.appliedAt.localeCompare(a.appliedAt));
  const newest = sorted[0]?.appliedAt ?? null;
  const props = generatedProps(
    'change-log',
    worldId,
    {
      month,
      changes: sorted.length,
      applied: sorted.filter(e => e.mode === 'apply').length,
      undone: sorted.filter(e => e.mode === 'apply' && e.undoneBy).length,
      features: [...new Set(sorted.map(e => e.feature))].sort(),
    },
    newest
  );
  const blocks = sorted.map(e => {
    const state =
      e.mode === 'undo'
        ? `undo of \`${e.undoOf ?? '?'}\``
        : e.undoneBy
          ? `undone by \`${e.undoneBy}\` at ${shortTime(e.undoneAt)}`
          : 'applied';
    return [
      `### ${shortTime(e.appliedAt)} · ${neutralizeTemplater(e.summary)}`,
      '',
      `- Change \`${e.changeId}\` · feature **${neutralizeTemplater(e.feature)}** · ${e.mode} · risk ${e.risk} · written to ${e.target}`,
      `- State: ${state}`,
      '',
      callout(
        'note',
        `Diff (${e.diff.length} line(s), GM only)`,
        e.diff.map(d => `- ${d}`)
      ),
      '',
      `^${e.changeId}`,
      '',
    ].join('\n');
  });
  return withGeneratedHash(
    [
      frontmatter(props),
      `# Changes ${month}`,
      '',
      GENERATED_BANNER,
      '',
      'Every change the AI Tool applied or undid through guarded writes (times in UTC). Undo from the dashboard (Recent Changes).',
      '',
      ...blocks,
    ].join('\n')
  );
}

// ---------------------------------------------------------------------------
// Tarokka
// ---------------------------------------------------------------------------

export interface TarokkaPositionData {
  cardId: string;
  cardName: string;
  gmNote: string | null;
  revealed: boolean;
  revealPageUuid?: string;
}

export interface TarokkaReadingData {
  readingId: string;
  source: string;
  readAt: string;
  positions: Record<string, TarokkaPositionData>;
}

export interface TarokkaLinks {
  journalPageUuid?: string;
  sceneUuid?: string;
  actorUuid?: string;
}

const POSITIONS: Array<[string, string]> = [
  ['tome', 'Tome'],
  ['holySymbol', 'Holy symbol'],
  ['sunsword', 'Sunsword'],
  ['ally', 'Ally'],
  ['strahdLocation', "Strahd's location"],
];

interface TarokkaRenderOptions {
  links?: Partial<Record<string, Record<string, TarokkaLinks>>>;
  cardNames?: Record<string, string>;
}

function tarokkaPositionSections(
  reading: TarokkaReadingData,
  options: TarokkaRenderOptions
): { sections: string[]; revealed: number; linked: number } {
  const sections: string[] = [];
  let revealed = 0;
  let linked = 0;
  for (const [key, label] of POSITIONS) {
    const p = reading.positions[key];
    if (!p) continue;
    const name = options.cardNames?.[p.cardId] ?? p.cardName;
    const links = options.links?.[key]?.[p.cardId] ?? {};
    const linkLines = [
      links.journalPageUuid ? `- Journal page: \`${links.journalPageUuid}\`` : null,
      links.sceneUuid ? `- Scene: \`${links.sceneUuid}\`` : null,
      links.actorUuid ? `- Actor: \`${links.actorUuid}\`` : null,
    ].filter((l): l is string => l !== null);
    if (linkLines.length) linked += 1;
    if (p.revealed) revealed += 1;
    sections.push(
      [
        `## ${label}`,
        '',
        callout('danger', 'Card (GM secret)', [
          `**${name}** (\`${p.cardId}\`)`,
          ...(p.gmNote ? ['', `GM note: ${p.gmNote}`] : []),
        ]),
        '',
        `- Revealed to players: ${p.revealed ? `yes (page \`${p.revealPageUuid ?? '?'}\`)` : 'no'}`,
        ...(linkLines.length ? linkLines : ['- Not linked yet (link it in the dashboard)']),
        '',
      ].join('\n')
    );
  }
  return { sections, revealed, linked };
}

/** The current reading (GM only): cards hidden in collapsed callouts, links,
 * reveals, and links to any archived readings' own notes. */
export function renderTarokkaNote(
  worldId: string,
  reading: TarokkaReadingData | null,
  options: TarokkaRenderOptions & {
    archived?: string[];
    revealJournalUuid?: string | null;
  } = {}
): string {
  if (!reading) {
    const props = generatedProps('tarokka-reading', worldId, { reading_id: null }, null);
    return withGeneratedHash(
      [
        frontmatter(props),
        '# Tarokka reading',
        '',
        GENERATED_BANNER,
        '',
        'No reading is stored yet. Deal or import one from the dashboard (🃏 Tarokka).',
        '',
      ].join('\n')
    );
  }
  const { sections, revealed, linked } = tarokkaPositionSections(reading, options);
  const props = generatedProps(
    'tarokka-reading',
    worldId,
    {
      reading_id: reading.readingId,
      source: reading.source,
      read_at: shortTime(reading.readAt),
      revealed_count: revealed,
      linked_count: linked,
      archived_readings: options.archived?.length ?? 0,
      reveal_journal: options.revealJournalUuid ?? null,
    },
    reading.readAt
  );
  const archiveLinks = options.archived?.length
    ? [
        '## Archive',
        '',
        ...options.archived.map(id => `- [${id}](Archive/${safeFileName(id)}.md)`),
        '',
      ]
    : [];
  return withGeneratedHash(
    [
      frontmatter(props),
      '# Tarokka reading',
      '',
      GENERATED_BANNER,
      '',
      'GM only. The reading lives in the bridge vault, never in Foundry world data. Card names are in collapsed callouts so they do not show at a glance.',
      '',
      ...sections,
      ...archiveLinks,
    ].join('\n')
  );
}

/** One note per archived reading: `AI Tool/Tarokka/Archive/<readingId>.md`. */
export function renderTarokkaArchiveNote(
  worldId: string,
  reading: TarokkaReadingData,
  options: TarokkaRenderOptions = {}
): string {
  const { sections, revealed, linked } = tarokkaPositionSections(reading, options);
  const props = generatedProps(
    'tarokka-reading',
    worldId,
    {
      reading_id: reading.readingId,
      source: reading.source,
      read_at: shortTime(reading.readAt),
      revealed_count: revealed,
      linked_count: linked,
      archived: true,
    },
    reading.readAt
  );
  return withGeneratedHash(
    [
      frontmatter(props),
      `# Tarokka reading (archived) ${reading.readingId}`,
      '',
      GENERATED_BANNER,
      '',
      'GM only. This reading was replaced by a later one; the bridge vault keeps it in `gm/tarokka.json` archive.',
      '',
      ...sections,
    ].join('\n')
  );
}

const CANVAS_NODE_W = 320;
const CANVAS_NODE_H = 220;
/** Cross layout: holySymbol top, tome left, strahdLocation centre, sunsword right, ally bottom. */
const CANVAS_LAYOUT: Record<string, { x: number; y: number }> = {
  holySymbol: { x: 0, y: -300 },
  tome: { x: -460, y: 0 },
  strahdLocation: { x: 0, y: 0 },
  sunsword: { x: 460, y: 0 },
  ally: { x: 0, y: 300 },
};

function canvasNode(
  id: string,
  text: string,
  x: number,
  y: number,
  width: number,
  height: number,
  color?: string
): { id: string; [key: string]: unknown } {
  const node: { id: string; [key: string]: unknown } = {
    id,
    type: 'text',
    text,
    x,
    y,
    width,
    height,
  };
  if (color !== undefined) node.color = color;
  return node;
}

/** `AI Tool/Tarokka/Spread.canvas` (JSON Canvas 1.0): one text node per
 * position laid out as a cross, plus the ownership marker node. */
export function renderSpreadCanvas(
  reading: TarokkaReadingData | null,
  cardNames: Record<string, string> = {}
): string {
  const nodes: Array<{ id: string; [key: string]: unknown }> = [];
  if (reading) {
    for (const [key, label] of POSITIONS) {
      const p = reading.positions[key];
      const pos = CANVAS_LAYOUT[key];
      if (!p || !pos) continue;
      const name = cardNames[p.cardId] ?? p.cardName;
      const text = [
        `## ${label}`,
        '',
        callout('danger', 'Card (GM secret)', [
          `**${name}** (\`${p.cardId}\`)`,
          ...(p.gmNote ? ['', `GM note: ${p.gmNote}`] : []),
        ]),
        '',
        `Revealed: ${p.revealed ? 'yes' : 'no'}`,
      ].join('\n');
      nodes.push(
        canvasNode(
          key,
          text,
          pos.x,
          pos.y,
          CANVAS_NODE_W,
          CANVAS_NODE_H,
          p.revealed ? '4' : undefined
        )
      );
    }
  } else {
    nodes.push(canvasNode('no-reading', 'No reading yet', 0, 0, CANVAS_NODE_W, CANVAS_NODE_H));
  }
  nodes.push(canvasNode('generated', '', -300, -620, 900, 110));
  const doc: CanvasMarkerDoc = { nodes, edges: [] };
  return withCanvasHash(doc, GENERATED_BANNER);
}

// ---------------------------------------------------------------------------
// Bases (AI Tool/Bases/*.base)
// ---------------------------------------------------------------------------

function baseBody(lines: string[]): string {
  return `${lines.join('\n')}\n`;
}

/** `AI Tool/Bases/Sessions.base`: a table over the session notes. */
export function renderSessionsBase(worldId: string): string {
  return renderBaseText(
    baseBody([
      'filters:',
      '  and:',
      `    - file.inFolder("Campaigns/${worldId}/AI Tool/Sessions")`,
      '    - file.hasTag("session")',
      'views:',
      '  - type: table',
      '    name: Sessions',
      '    order:',
      '      - file.name',
      '      - date',
      '      - session_number',
      '      - started_at',
      '      - ended_at',
      '      - duration_min',
      '      - events',
      '      - changes',
      '      - actors',
      '      - scenes',
      '    sort:',
      '      - property: date',
      '        direction: DESC',
      '      - property: session_number',
      '        direction: DESC',
    ])
  );
}

/** `AI Tool/Bases/Changes.base`: a table over the monthly change-log notes. */
export function renderChangesBase(worldId: string): string {
  return renderBaseText(
    baseBody([
      'filters:',
      '  and:',
      `    - file.inFolder("Campaigns/${worldId}/AI Tool/Changes")`,
      '    - file.hasTag("change-log")',
      'views:',
      '  - type: table',
      '    name: Changes by month',
      '    order:',
      '      - file.name',
      '      - month',
      '      - changes',
      '      - applied',
      '      - undone',
      '    sort:',
      '      - property: month',
      '        direction: DESC',
    ])
  );
}

/** `AI Tool/Bases/Tarokka readings.base`: a table over the current and archived readings. */
export function renderTarokkaReadingsBase(worldId: string): string {
  return renderBaseText(
    baseBody([
      'filters:',
      '  and:',
      `    - file.inFolder("Campaigns/${worldId}/AI Tool/Tarokka")`,
      '    - file.hasTag("tarokka-reading")',
      'views:',
      '  - type: table',
      '    name: Tarokka readings',
      '    order:',
      '      - file.name',
      '      - reading_id',
      '      - source',
      '      - read_at',
      '      - revealed_count',
      '      - linked_count',
      '      - archived',
      '    sort:',
      '      - property: read_at',
      '        direction: DESC',
    ])
  );
}

/** `AI Tool/Bases/PC stats.base`: a table over the per-PC stats notes. */
export function renderPcStatsBase(worldId: string): string {
  return renderBaseText(
    baseBody([
      'filters:',
      '  and:',
      `    - file.inFolder("Campaigns/${worldId}/AI Tool/Stats/PCs")`,
      '    - file.hasTag("pc-stats")',
      'views:',
      '  - type: table',
      '    name: PC stats',
      '    order:',
      '      - file.name',
      '      - sessions',
      '      - damage_dealt',
      '      - damage_taken',
      '      - healing_received',
      '      - downs',
      '      - kills',
      '      - rolls',
      '      - crits',
      '      - fumbles',
      '      - spells_cast',
      '      - xp_gained',
      '    sort:',
      '      - property: file.name',
      '        direction: ASC',
    ])
  );
}

// ---------------------------------------------------------------------------
// Stats (AI Tool/Stats/*, docs/design/OBSIDIAN-PLAN.md section 8, O3)
// ---------------------------------------------------------------------------

/** A Tally as a two-column Markdown table, or `(none)` when empty. */
function tallyTable(tally: Tally, keyHeader: string): string[] {
  const entries = Object.entries(tally);
  if (entries.length === 0) return ['(none)', ''];
  return [
    `| ${keyHeader} | Amount |`,
    '| --- | --- |',
    ...entries.map(([key, amount]) => `| ${cell(key)} | ${amount} |`),
    '',
  ];
}

/** The 1..20 natural d20 distribution as one table, values 1..20 left to right. */
function d20SpreadTable(d20: readonly number[]): string[] {
  const header = Array.from({ length: 20 }, (_, i) => `${i + 1}`);
  return [
    `| ${header.join(' | ')} |`,
    `| ${header.map(() => '---').join(' | ')} |`,
    `| ${d20.map(n => `${n}`).join(' | ')} |`,
    '',
  ];
}

/** `AI Tool/Stats/Campaign.md`: campaign totals, sessions, PCs, the d20
 * spread and per-user dice, derived from the play log (contract 5). */
export function renderCampaignStatsNote(
  worldId: string,
  stats: StatsModel,
  options: {
    usageNote?: boolean;
    /** Labels of the sessions that have a note in `AI Tool/Sessions/` (their rows link it). */
    sessionNotes?: ReadonlySet<string>;
    /** PC uuid to the file name of its note in `AI Tool/Stats/PCs/` (its row links it). */
    pcNotes?: ReadonlyMap<string, string>;
  } = {}
): string {
  const c = stats.campaign;
  const props = generatedProps(
    'campaign-stats',
    worldId,
    {
      sessions: c.sessions,
      play_minutes: c.playMinutes,
      combats: c.combats,
      rounds: c.rounds,
      pc_downs: c.pcDowns,
      npc_kills: c.npcKills,
      rolls: c.rolls,
      crits: c.crits,
      fumbles: c.fumbles,
      spells_cast: c.spellsCast,
      game_seconds: c.gameSeconds,
    },
    c.lastRecordAt
  );
  // Links in table cells: Markdown links (no `|`), relative to `AI Tool/Stats/`.
  const sessionCell = (label: string): string =>
    options.sessionNotes?.has(label)
      ? `[${cell(label)}](../Sessions/${encodeSegment(`${label}.md`)})`
      : cell(label);
  const pcCell = (pc: PcStats): string => {
    const file = options.pcNotes?.get(pc.uuid);
    const text = cell(pc.name).replace(/[[\]]/g, '\\$&');
    return file ? `[${text}](PCs/${encodeSegment(`${file}.md`)})` : cell(pc.name);
  };
  const sessionRows = stats.sessions.map(
    s =>
      `| ${sessionCell(s.label)} | ${s.durationMin} | ${s.combats.length} | ${s.partyDamageDealt} | ${s.partyDamageTaken} | ${s.partyHealing} | ${s.pcDowns} | ${s.npcKills} | ${s.rolls} |`
  );
  const pcRows = stats.pcs.map(
    (p: PcStats) =>
      `| ${pcCell(p)} | ${p.sessions.length} | ${p.damageDealt} | ${p.damageTaken} | ${p.healingReceived} | ${p.downs} | ${p.kills} | ${p.rolls} | ${p.crits} | ${p.fumbles} | ${p.spellsCast} | ${p.xpGained} |`
  );
  const userRows = Object.entries(stats.dice.byUser).map(
    ([name, u]) => `| ${cell(name)} | ${u.rolls} | ${u.nat20} | ${u.nat1} | ${u.average} |`
  );
  return withGeneratedHash(
    [
      frontmatter(props),
      '# Campaign stats',
      '',
      GENERATED_BANNER,
      '',
      'Derived from the raw play log (never from state); rebuilt on every export. ' +
        'Damage and healing count HP changes, never damage rolls, so nothing here double-counts.',
      '',
      '## Sessions',
      '',
      '| Session | Minutes | Combats | Dmg dealt | Dmg taken | Healing | Downs | Kills | Rolls |',
      '| --- | --- | --- | --- | --- | --- | --- | --- | --- |',
      ...(sessionRows.length ? sessionRows : ['| (none) | | | | | | | | |']),
      '',
      '## PCs',
      '',
      '| PC | Sessions | Dmg dealt | Dmg taken | Healing | Downs | Kills | Rolls | Crits | Fumbles | Spells | XP |',
      '| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |',
      ...(pcRows.length ? pcRows : ['| (none) | | | | | | | | | | | |']),
      '',
      '## d20 spread (1-20)',
      '',
      ...d20SpreadTable(stats.dice.d20),
      '## Per-user dice',
      '',
      '| User | Rolls | Nat 20 | Nat 1 | Average |',
      '| --- | --- | --- | --- | --- |',
      ...(userRows.length ? userRows : ['| (none) | | | | |']),
      '',
      ...(options.usageNote
        ? ['## Dashboard usage', '', 'Which controls get used: [[Dashboard usage]].', '']
        : []),
    ].join('\n')
  );
}

/** `AI Tool/Stats/PCs/<PC name>.md`: one PC's totals, d20 spread, slots,
 * resources, loot and currency. PC and item names are player-chosen, so every
 * line of body text goes through `cell`/`neutralizeTemplater`. */
export function renderPcStatsNote(worldId: string, pc: PcStats): string {
  const props = generatedProps(
    'pc-stats',
    worldId,
    {
      fvtt_uuid: pc.uuid,
      sessions: pc.sessions.length,
      damage_dealt: pc.damageDealt,
      damage_taken: pc.damageTaken,
      healing_received: pc.healingReceived,
      downs: pc.downs,
      kills: pc.kills,
      rolls: pc.rolls,
      crits: pc.crits,
      fumbles: pc.fumbles,
      spells_cast: pc.spellsCast,
      items_used: pc.itemsUsed,
      xp_gained: pc.xpGained,
    },
    null
  );
  return withGeneratedHash(
    [
      frontmatter(props),
      `# ${neutralizeTemplater(pc.name)} stats`,
      '',
      GENERATED_BANNER,
      '',
      `Sessions: ${pc.sessions.length ? pc.sessions.map(n => `S${sessionLabel(n)}`).join(', ') : '(none)'}.`,
      '',
      '## d20 spread (1-20)',
      '',
      ...d20SpreadTable(pc.d20),
      '## Spell slots spent',
      '',
      ...tallyTable(pc.slotsSpent, 'Slot'),
      '## Resources spent',
      '',
      ...tallyTable(pc.resourcesSpent, 'Resource'),
      '## Loot gained',
      '',
      ...tallyTable(pc.lootGained, 'Item'),
      '## Currency change',
      '',
      ...tallyTable(pc.currencyDelta, 'Denomination'),
    ].join('\n')
  );
}

// ---------------------------------------------------------------------------
// Status (AI Tool/_status.md, written last on every export)
// ---------------------------------------------------------------------------

export interface ExportStatusInput {
  /** Notes this export produced (not counting `_status.md` itself). */
  notesManaged: number;
  skipped: Array<{ path: string; reason: string }>;
  /** GM-owned notes kept as the GM edited them (an edited Home): a standing note. */
  kept?: Array<{ path: string; reason: string }>;
  errors: Array<{ path: string; error: string }>;
}

/** `AI Tool/_status.md`: how many notes the tool manages, the GM's own notes it keeps as
 * edited, the ones it skipped (edited in Obsidian, or foreign) and errors. Only lasting facts (no times, no
 * per-run counts), so it is not rewritten on every render. */
export function renderStatusNote(worldId: string, status: ExportStatusInput): string {
  const skipped = [...status.skipped].sort((a, b) => a.path.localeCompare(b.path));
  const errors = [...status.errors].sort((a, b) => a.path.localeCompare(b.path));
  const kept = [...(status.kept ?? [])].sort((a, b) => a.path.localeCompare(b.path));
  const props = generatedProps(
    'status',
    worldId,
    {
      notes_managed: status.notesManaged,
      notes_skipped: skipped.length,
      notes_errored: errors.length,
    },
    null
  );
  return withGeneratedHash(
    [
      frontmatter(props),
      '# AI Tool status',
      '',
      GENERATED_BANNER,
      '',
      `The AI Tool manages ${status.notesManaged} note(s) here. Notes it no longer produces go to the vault trash.`,
      '',
      'The Foundry mirror keeps its own status in [Foundry/_status.md](Foundry/_status.md); that note exists only when the mirror is on.',
      '',
      ...(kept.length
        ? [
            '## Your own notes (kept as you edited them)',
            '',
            'Nothing to fix here: the tool leaves these as they are.',
            '',
            ...kept.map(k => `- \`${k.path}\`: ${k.reason}`),
            '',
          ]
        : []),
      '## Skipped (edited in Obsidian, or foreign)',
      '',
      ...(skipped.length ? skipped.map(s => `- \`${s.path}\`: ${s.reason}`) : ['- (none)']),
      '',
      '## Errors',
      '',
      ...(errors.length ? errors.map(e => `- \`${e.path}\`: ${e.error}`) : ['- (none)']),
      '',
    ].join('\n')
  );
}

// ---------------------------------------------------------------------------
// Campaign home (created once, then the GM's)
// ---------------------------------------------------------------------------

/**
 * The campaign's Home note: written when missing, and over an older template the GM never
 * edited (`campaign-home-legacy.ts`); an edited Home is never overwritten.
 */
export function renderCampaignHome(worldId: string): string {
  const base = (folder: string, name: string, columns: string[], sortBy: string): string =>
    [
      '```base',
      'filters:',
      '  and:',
      `    - file.inFolder("Campaigns/${worldId}/AI Tool/${folder}")`,
      'views:',
      '  - type: table',
      `    name: ${name}`,
      '    order:',
      ...columns.map(c => `      - ${c}`),
      '    sort:',
      `      - property: ${sortBy}`,
      '        direction: DESC',
      '```',
    ].join('\n');
  return [
    frontmatter({ type: 'campaign-home', world: worldId }),
    `# ${worldId}`,
    '',
    'Home of this campaign in Obsidian. This note is yours: the AI Tool created it, and once you edit it the tool never rewrites it.',
    '',
    '- `AI Tool/` is written by the bridge (session logs, change log, Tarokka). Read-only view; rebuilt on export.',
    '- `Prep/` is yours: session plans, NPCs, locations, ideas. The tool never writes there.',
    '',
    '## Adventures',
    '',
    'One hub note per adventure (a Foundry folder with chapters and scenes), linking its chapters, scenes, NPCs and story items. The hubs appear once the Foundry mirror has run.',
    '',
    [
      '```base',
      'filters:',
      '  and:',
      `    - file.inFolder("Campaigns/${worldId}/AI Tool/Foundry/Adventures")`,
      'views:',
      '  - type: table',
      '    name: Adventures',
      '    order:',
      '      - file.name',
      '      - book',
      '    sort:',
      '      - property: file.name',
      '        direction: ASC',
      '```',
    ].join('\n'),
    '',
    '## Sessions',
    '',
    base('Sessions', 'Session logs', ['file.name', 'date', 'events', 'changes', 'actors'], 'date'),
    '',
    '## Change log',
    '',
    base('Changes', 'Changes by month', ['file.name', 'changes', 'applied', 'undone'], 'month'),
    '',
    '## Tarokka',
    '',
    '- [Current reading](AI%20Tool/Tarokka/Current%20reading.md)',
    '',
    '## Foundry',
    '',
    'When the Foundry mirror is on, `AI Tool/Foundry/` holds one note per PC, NPC, scene, journal and story item, rebuilt from Foundry. The bases below and the status note appear once the mirror has run.',
    '',
    '- [PCs](AI%20Tool/Bases/PCs.base)',
    '- [NPCs](AI%20Tool/Bases/NPCs.base)',
    '- [Scenes](AI%20Tool/Bases/Scenes.base)',
    '- [Journals](AI%20Tool/Bases/Journals.base)',
    '- [Story items](AI%20Tool/Bases/Story%20items.base)',
    '- [Player visible](AI%20Tool/Bases/Player%20visible.base)',
    '- [Mirror status](AI%20Tool/Foundry/_status.md)',
    '',
    '## Bases',
    '',
    '- [Sessions](AI%20Tool/Bases/Sessions.base)',
    '- [Changes](AI%20Tool/Bases/Changes.base)',
    '- [Tarokka readings](AI%20Tool/Bases/Tarokka%20readings.base)',
    '',
  ].join('\n');
}
