/**
 * Obsidian notes rendered from the bridge vault (docs/OBSIDIAN-PLAN.md, O1).
 *
 * Pure functions: vault data in, Markdown out. The bridge vault JSON stays the
 * source of truth; these notes are a read-only, GM-only view of it that the
 * exporter writes into the GM's Obsidian vault under
 * `Campaigns/<worldId>/AI Tool/`. Output is deterministic (no timestamps of
 * the export itself), so an unchanged note is not rewritten while the GM has
 * it open.
 *
 * Conventions: flat YAML properties (text, number, checkbox, list), Markdown
 * links (the vault uses them so repo docs work too), a banner on every note
 * saying it is generated, and secrets (card names, diffs that may contain
 * them) inside collapsed callouts so they do not show at a glance on screen.
 */

export const GENERATED_BANNER =
  '> [!info] Generated by the Foundry AI Tool\n' +
  '> This note is rebuilt from the bridge vault on every export; edits here are lost. ' +
  'Write your own notes in `Prep/`.';

type PropValue = string | number | boolean | null | readonly string[];

function yamlScalar(value: string | number | boolean | null): string {
  if (value === null) return 'null';
  if (typeof value === 'number' || typeof value === 'boolean') return String(value);
  // Quote everything textual: safe for colons, links, leading symbols.
  return JSON.stringify(value);
}

/** A YAML properties block (flat keys only, as Obsidian properties expect). */
export function frontmatter(props: Record<string, PropValue | undefined>): string {
  const lines = ['---'];
  for (const [key, value] of Object.entries(props)) {
    if (value === undefined) continue;
    if (Array.isArray(value)) {
      const list = value as readonly string[];
      if (list.length === 0) {
        lines.push(`${key}: []`);
      } else {
        lines.push(`${key}:`);
        for (const item of list) lines.push(`  - ${yamlScalar(item)}`);
      }
    } else {
      lines.push(`${key}: ${yamlScalar(value as string | number | boolean | null)}`);
    }
  }
  lines.push('---');
  return lines.join('\n');
}

/** Text safe inside a Markdown table cell. */
export function cell(value: unknown): string {
  const text =
    typeof value === 'string' ? value : value === null || value === undefined ? '' : String(value);
  return text.replace(/\r?\n/g, ' ').replace(/\|/g, '\\|').trim();
}

/** A string safe as a file name on Windows, Linux and in Obsidian links. */
export function safeFileName(name: string): string {
  const printable = Array.from(name, ch => (ch.charCodeAt(0) < 32 ? ' ' : ch)).join('');
  const cleaned = printable
    .replace(/[<>:"/\\|?*#^[\]%]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .replace(/[. ]+$/, '');
  const reserved = /^(con|prn|aux|nul|com\d|lpt\d)$/i;
  if (!cleaned || reserved.test(cleaned)) return `_${cleaned || 'untitled'}`;
  return cleaned.slice(0, 120);
}

function callout(type: string, title: string, body: string[], collapsed = true): string {
  const head = `> [!${type}]${collapsed ? '-' : ''} ${title}`;
  const lines = body.length ? body : ['(empty)'];
  return [head, ...lines.map(l => (l ? `> ${l}` : '>'))].join('\n');
}

/** "2026-09-28T09:52:27.308Z" -> "2026-09-28 09:52" (UTC, stable across hosts). */
function shortTime(iso: string | undefined): string {
  if (!iso) return '';
  return iso.replace('T', ' ').slice(0, 16);
}

// ---------------------------------------------------------------------------
// Session log
// ---------------------------------------------------------------------------

export interface SessionEvent {
  id?: string;
  timestamp?: string;
  eventType?: string;
  actorName?: string | null;
  description?: string;
  details?: Record<string, unknown> | null;
}

/** One note per day of the backend's session log (`sessions/<date>.jsonl`). */
export function renderSessionNote(worldId: string, date: string, events: SessionEvent[]): string {
  const sorted = [...events].sort((a, b) =>
    String(a.timestamp ?? '').localeCompare(String(b.timestamp ?? ''))
  );
  const types = [...new Set(sorted.map(e => e.eventType ?? 'event'))].sort();
  const actors = [
    ...new Set(sorted.map(e => e.actorName).filter((n): n is string => Boolean(n))),
  ].sort();
  const changeIds = sorted
    .map(e => e.details?.changeId)
    .filter((id): id is string => typeof id === 'string');
  const props = frontmatter({
    type: 'session-log',
    world: worldId,
    date,
    events: sorted.length,
    first_event: shortTime(sorted[0]?.timestamp),
    last_event: shortTime(sorted[sorted.length - 1]?.timestamp),
    event_types: types,
    actors,
    changes: changeIds.length,
    generated: true,
  });
  const rows = sorted.map(e => {
    const change = typeof e.details?.changeId === 'string' ? ` (${e.details.changeId})` : '';
    return `| ${cell(shortTime(e.timestamp).slice(11))} | ${cell(e.eventType)} | ${cell(e.actorName)} | ${cell(`${e.description ?? ''}${change}`)} |`;
  });
  return [
    props,
    `# Session log ${date}`,
    '',
    GENERATED_BANNER,
    '',
    `${sorted.length} event(s) recorded by the bridge (times in UTC). Changes link to [the change log](../Changes/${date.slice(0, 7)}.md).`,
    '',
    '| Time | Type | Who | What |',
    '| --- | --- | --- | --- |',
    ...rows,
    '',
  ].join('\n');
}

// ---------------------------------------------------------------------------
// Change log (audit)
// ---------------------------------------------------------------------------

export interface ChangeEntry {
  changeId: string;
  feature: string;
  summary: string;
  risk: string;
  target: string;
  mode: 'apply' | 'undo';
  appliedAt: string;
  diff: string[];
  undoOf?: string;
  undoneBy?: string;
  undoneAt?: string;
}

/** One note per month of applied and undone guarded changes, newest first. */
export function renderChangesNote(worldId: string, month: string, entries: ChangeEntry[]): string {
  const sorted = [...entries].sort((a, b) => b.appliedAt.localeCompare(a.appliedAt));
  const props = frontmatter({
    type: 'change-log',
    world: worldId,
    month,
    changes: sorted.length,
    applied: sorted.filter(e => e.mode === 'apply').length,
    undone: sorted.filter(e => e.mode === 'apply' && e.undoneBy).length,
    features: [...new Set(sorted.map(e => e.feature))].sort(),
    generated: true,
  });
  const blocks = sorted.map(e => {
    const state =
      e.mode === 'undo'
        ? `undo of \`${e.undoOf ?? '?'}\``
        : e.undoneBy
          ? `undone by \`${e.undoneBy}\` at ${shortTime(e.undoneAt)}`
          : 'applied';
    return [
      `### ${shortTime(e.appliedAt)} · ${e.summary}`,
      '',
      `- Change \`${e.changeId}\` · feature **${e.feature}** · ${e.mode} · risk ${e.risk} · written to ${e.target}`,
      `- State: ${state}`,
      '',
      callout(
        'note',
        `Diff (${e.diff.length} line(s), GM only)`,
        e.diff.map(d => `- ${d}`)
      ),
      '',
    ].join('\n');
  });
  return [
    props,
    `# Changes ${month}`,
    '',
    GENERATED_BANNER,
    '',
    'Every change the AI Tool applied or undid through guarded writes (times in UTC). Undo from the co-GM dashboard (Recent Changes).',
    '',
    ...blocks,
  ].join('\n');
}

// ---------------------------------------------------------------------------
// Tarokka
// ---------------------------------------------------------------------------

export interface TarokkaPositionData {
  cardId: string;
  cardName: string;
  gmNote: string | null;
  revealed: boolean;
  revealPageUuid?: string;
}

export interface TarokkaReadingData {
  readingId: string;
  source: string;
  readAt: string;
  positions: Record<string, TarokkaPositionData>;
}

export interface TarokkaLinks {
  journalPageUuid?: string;
  sceneUuid?: string;
  actorUuid?: string;
}

const POSITIONS: Array<[string, string]> = [
  ['tome', 'Tome'],
  ['holySymbol', 'Holy symbol'],
  ['sunsword', 'Sunsword'],
  ['ally', 'Ally'],
  ['strahdLocation', "Strahd's location"],
];

/** The current reading (GM only): cards hidden in collapsed callouts, links and reveals. */
export function renderTarokkaNote(
  worldId: string,
  reading: TarokkaReadingData | null,
  options: {
    links?: Partial<Record<string, Record<string, TarokkaLinks>>>;
    cardNames?: Record<string, string>;
    archived?: string[];
    revealJournalUuid?: string | null;
  } = {}
): string {
  if (!reading) {
    return [
      frontmatter({ type: 'tarokka-reading', world: worldId, reading_id: null, generated: true }),
      '# Tarokka reading',
      '',
      GENERATED_BANNER,
      '',
      'No reading is stored yet. Deal or import one from the co-GM dashboard (🃏 Tarokka).',
      '',
    ].join('\n');
  }
  const sections: string[] = [];
  let revealed = 0;
  let linked = 0;
  for (const [key, label] of POSITIONS) {
    const p = reading.positions[key];
    if (!p) continue;
    const name = options.cardNames?.[p.cardId] ?? p.cardName;
    const links = options.links?.[key]?.[p.cardId] ?? {};
    const linkLines = [
      links.journalPageUuid ? `- Journal page: \`${links.journalPageUuid}\`` : null,
      links.sceneUuid ? `- Scene: \`${links.sceneUuid}\`` : null,
      links.actorUuid ? `- Actor: \`${links.actorUuid}\`` : null,
    ].filter((l): l is string => l !== null);
    if (linkLines.length) linked += 1;
    if (p.revealed) revealed += 1;
    sections.push(
      [
        `## ${label}`,
        '',
        callout('danger', 'Card (GM secret)', [
          `**${name}** (\`${p.cardId}\`)`,
          ...(p.gmNote ? ['', `GM note: ${p.gmNote}`] : []),
        ]),
        '',
        `- Revealed to players: ${p.revealed ? `yes (page \`${p.revealPageUuid ?? '?'}\`)` : 'no'}`,
        ...(linkLines.length ? linkLines : ['- Not linked yet (link it in the dashboard)']),
        '',
      ].join('\n')
    );
  }
  return [
    frontmatter({
      type: 'tarokka-reading',
      world: worldId,
      reading_id: reading.readingId,
      source: reading.source,
      read_at: shortTime(reading.readAt),
      revealed_count: revealed,
      linked_count: linked,
      archived_readings: options.archived?.length ?? 0,
      reveal_journal: options.revealJournalUuid ?? null,
      generated: true,
    }),
    '# Tarokka reading',
    '',
    GENERATED_BANNER,
    '',
    'GM only. The reading lives in the bridge vault, never in Foundry world data. Card names are in collapsed callouts so they do not show at a glance.',
    '',
    ...sections,
    ...(options.archived?.length
      ? ['## Archive', '', ...options.archived.map(id => `- \`${id}\``), '']
      : []),
  ].join('\n');
}

// ---------------------------------------------------------------------------
// Campaign home (created once, then the GM's)
// ---------------------------------------------------------------------------

/** The campaign's Home note: written only if missing, never overwritten. */
export function renderCampaignHome(worldId: string): string {
  const base = (folder: string, name: string, columns: string[], sortBy: string): string =>
    [
      '```base',
      'filters:',
      '  and:',
      `    - file.inFolder("Campaigns/${worldId}/AI Tool/${folder}")`,
      'views:',
      '  - type: table',
      `    name: ${name}`,
      '    order:',
      ...columns.map(c => `      - ${c}`),
      '    sort:',
      `      - property: ${sortBy}`,
      '        direction: DESC',
      '```',
    ].join('\n');
  return [
    frontmatter({ type: 'campaign-home', world: worldId }),
    `# ${worldId}`,
    '',
    'Home of this campaign in Obsidian. This note is yours: the AI Tool created it once and never rewrites it.',
    '',
    '- `AI Tool/` is written by the bridge (session logs, change log, Tarokka). Read-only view; rebuilt on export.',
    '- `Prep/` is yours: session plans, NPCs, locations, ideas. The tool never writes there.',
    '',
    '## Sessions',
    '',
    base('Sessions', 'Session logs', ['file.name', 'events', 'changes', 'actors'], 'date'),
    '',
    '## Change log',
    '',
    base('Changes', 'Changes by month', ['file.name', 'changes', 'applied', 'undone'], 'month'),
    '',
    '## Tarokka',
    '',
    '- [Current reading](AI%20Tool/Tarokka/Current%20reading.md)',
    '',
  ].join('\n');
}
