// GENERATED by scripts/usage-catalog.mjs (npm run usage:catalog). Do not edit by hand.
import type { UsageCatalogEntry } from './usage.js';

export const USAGE_CATALOG: readonly UsageCatalogEntry[] = [];
