/**
 * The tool version. Generated by `scripts/sync-version.mjs` from the root package.json: do not
 * edit by hand (run `npm run version:sync`). The bridge and the Foundry module compare it to
 * detect a mismatched pair.
 */
export const TOOL_VERSION = '0.21.0';
